services:
  app:
    ports:
      - "${APP_PORT}:3000"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - node_modules
            - .next
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: .env
          target: /app/.env

  db:
    ports:
      - "3306:3306"
